### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by aldinokemal** [mi-lopez/laravel-sso#1]
can we use in different domain and different host/server ?

**Comment by mi-lopez** [comment]
The truth if you want a SSO I recomend to you use Laravel Sanctum https://laravel.com/docs/8.x/sanctum I wouldn't do not use this lib anymore.

With Sanctum you can control from wich subdomain do you want to accept requests and share the session between different websites (using the same domain).

I'm not sure if you can accept requests from different domains, maybe yes.
